spring.datasource.url=jdbc:postgresql://localhost:5432/ChatBot
spring.datasource.username=postgres
spring.datasource.password=Hiersonne1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=6099